# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 09:48
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
