# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beeexpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('single_day_pass', models.CharField(blank=True, max_length=120, null=True)),
                ('weekend_pass', models.CharField(blank=True, max_length=120, null=True)),
                ('single_day_pass_normal', models.CharField(blank=True, max_length=120, null=True)),
                ('weekend_pass_normal', models.CharField(blank=True, max_length=120, null=True)),
                ('beeclub_asso', models.CharField(blank=True, max_length=120, null=True)),
                ('which_club', models.CharField(blank=True, max_length=120, null=True)),
                ('event', models.CharField(blank=True, max_length=120, null=True)),
                ('dietary', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
