# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeexpo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beeexpo',
        ),
    ]
