# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
            ],
        ),
    ]
