# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=150)),
                ('contact_phone', models.CharField(max_length=13)),
                ('beeclub_asso', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('which_club', models.CharField(blank=True, max_length=150)),
                ('event', models.CharField(blank=True, choices=[('my bee club', 'My bee club'), ('email newsletter', 'Email newsletter'), ('word of mouth', 'Word of mouth'), ('facebook', 'Facebook'), ('advertsment', 'Advertsment'), ('other', 'Other')], max_length=100)),
                ('lunch', models.CharField(blank=True, max_length=150)),
                ('dietary', models.CharField(blank=True, max_length=150)),
                ('mailchimp_list', models.CharField(blank=True, max_length=150)),
                ('paid', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
