# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedup',
            name='single_day_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signedup',
            name='single_day_pass_normal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signedup',
            name='weekend_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signedup',
            name='weekend_pass_normal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
