# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20190411_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signedup',
            name='lunch',
        ),
    ]
