# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_signedup_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedup',
            name='dietary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='signedup',
            name='which_club',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
